; Generated by AutoGUI 2.5.9
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

FileInstall, Heatran.png, %a_temp%/back.png
FileInstall, mblaziico.ico, %a_temp%/favicon.ico

Menu Tray, Icon, %a_temp%/favicon.ico

username = macro
password = dog@pai

InputBox, user, Insira seu nome de usuario
InputBox,pass, Insira sua senha
If ( user <> username ) OR ( pass <> password )
  ExitApp
MsgBox Senha Correta, a macro abrira

Gui +Resize
Gui Add, Picture, x-18 y-27 w640 h480, %a_temp%/back.png
;----------------------------------------------------
;Group Heal
Gui Add, GroupBox, x2 y10 w140 h100, Heal
;----------------------------------------------------
;Revive
Gui Add, Button, x13 y22 w50 h20 gRev, &Revive
Gui Add, Hotkey, x63 y22 w40 h20 vvar1
Gui Add, Button, x103 y22 w30 h20 gOk1, &OK
;----------------------------------------------------
;Potion
Gui Add, Button, x13 y42 w50 h20 gPot, &Potion
Gui Add, Hotkey, x63 y42 w40 h20 vvar2
Gui Add, Button, x103 y42 w30 h20 gOk2, &OK
;----------------------------------------------------
;Medicine
Gui Add, Button, x13 y62 w50 h20 gMed, Medicine
Gui Add, Hotkey, x63 y62 w40 h20 vvar3
Gui Add, Button, x103 y62 w30 h20 gOk3, &OK
;----------------------------------------------------
;SMedicine
Gui Add, Button, x3 y82 w60 h20 gSmed, SMedicine
Gui Add, Hotkey, x63 y82 w40 h20 vvar4
Gui Add, Button, x103 y82 w30 h20 gOk4, &OK
;----------------------------------------------------
;Group Controles
Gui Add, GroupBox, x205 y9 w140 h100, Controles
;----------------------------------------------------
;WASD
Gui Add, Text, x210 y26 w33 h14, WASD
Gui Add, CheckBox, x243 y26 w57 h14 vCheck gCheck1, ON/OFF
;----------------------------------------------------
;Swap
Gui Add, Button, x210 y39 w50 h20 gSwap, Swap
Gui Add, Hotkey, x259 y40 w40 h20 vvar6
Gui Add, Button, x298 y40 w30 h20 gOk6, &OK
;----------------------------------------------------
;Loot
Gui Add, Button, x210 y59 w50 h20 gCorp, Loot
Gui Add, Hotkey, x260 y59 w40 h20 vvar11
Gui Add, Button, x300 y59 w30 h20 gOk11, &OK
;----------------------------------------------------
;Moveset
Gui Add, GroupBox, x382 y9 w140 h100, Auto Moveset
Gui Add, ComboBox, x411 y34 w85 vPoke, Chandelure|GiantKarp|Golem|ShEspeon|ShFearow|ShMime|Smeargle8Blizzard|Smeargle8Inferno|Smeargle8Spout|SmeargleGhost|SmeargleXatuAstonish|SmeargleXatuBlizzard|Tropius|Typhlosion|VoirGolden|VoirHeal
Gui Add, Hotkey, x424 y58 w50 h20 vvar5
Gui Add, Button, x423 y81 w50 h20 gOk5, Confirme
;----------------------------------------------------
;Elixirs
Gui Add, GroupBox, x2 y124 w140 h100, Elixirs
;----------------------------------------------------
;Healing
Gui Add, Button, x8 y138 w50 h20 gHeal, &Healing
Gui Add, Hotkey, x58 y138 w40 h20 vvar7
Gui Add, Button, x98 y137 w30 h20 gOk7, &OK
;----------------------------------------------------
;Attack
Gui Add, Button, x8 y157 w50 h20 gAttack, &Attack
Gui Add, Hotkey, x58 y157 w40 h20 vvar8
Gui Add, Button, x98 y156 w30 h20 gOk8, &OK
;----------------------------------------------------
;Defense
Gui Add, Button, x8 y176 w50 h20 gDefense, &Defense
Gui Add, Hotkey, x58 y176 w40 h20 vvar9
Gui Add, Button, x98 y175 w30 h20 gOk9, &OK
;----------------------------------------------------
;Running
Gui Add, Button, x8 y196 w50 h20 gRun, &Running
Gui Add, Hotkey, x58 y196 w40 h20 vvar10
Gui Add, Button, x98 y195 w30 h20 gOk10, &OK
;----------------------------------------------------
;Fishing
Gui Add, GroupBox, x203 y126 w140 h100, Fishing
Gui Add, Text, x206 y142 w126 h12 +0x200, Indique o tempo de espera
Gui Add, Text, x204 y154 w137 h13, para a pesca (em segundos!)
Gui Add, Edit, x210 y168 w40 h20 +Number vvard
Gui Add, Button, x258 y169 w50 h20 gFish, &Fishing
Gui Add, Text, x206 y192 w126 h12 +0x200, Para ativar a pesca Ctrl+J
;----------------------------------------------------
;Trade
Gui Add, GroupBox, x381 y134 w140 h100, Trade
Gui Add, Text, x382 y148 w138 h15 +0x200, Indique a Hotkey para enviar
Gui Add, Text, x388 y162 w127 h12 +0x200, a mensagem Trade Center
Gui Add, Hotkey, x423 y176 w45 h17 vvart
Gui Add, CheckBox, x412 y194 w64 h12 vmsg gmsgin, ON / OFF
;----------------------------------------------------
;Exit
gui Add,Text,x380 y340,Para Pausar Aperte Ctrl + H.
gui, add, button, x400 y353 h30 w80 gexit, Exit Script
;----------------------------------------------------

Gui Show, w540 h400, Macro Smart
Return

GuiSize:
    If (A_EventInfo == 1) {
        Return
    }

Return

GuiClose:
exit:
 {
   exitapp
 }
return
	
Ok1:
Gui, Submit, NoHide
Hotkey, %var1%, action1, On
return
Rev:
{
MsgBox ,48 , , Selecione a Pokeball que vai se usar o Revive, 10
KeyWait, LButton, D
MouseGetPos, Bp1X, Bp1Y
MsgBox ,48 , , Selecione a pos do Revive, 10
KeyWait, LButton, D
MouseGetPos, Bp2X, Bp2Y
Sleep, 200
action1:
  {
    MouseGetPos, xpos, ypos
    MouseClick, right, %Bp1X%, %Bp1Y%, ,0
    Sleep, 230
    MouseClick, right, %Bp2X%, %Bp2Y%, ,0
    Sleep, 230
    MouseClick, left, %Bp1X%, %Bp1Y%, ,0
    Sleep, 230
    MouseClick, right, %Bp1X%, %Bp1Y%, ,0
    MouseMove, %xpos%,%ypos%
    return
  } 
}
return
;-----------------------------------------------
Ok2:
Gui, Submit, NoHide
Hotkey, %var2%, action2, On
return
Pot:
{
MsgBox ,48 , , Selecione a pos de seu POke no Battle, 10
KeyWait, LButton, D
MouseGetPos, B1X, B1Y
MsgBox ,48 , , Selecione a pos da Potion em sua Backpack, 10
KeyWait, LButton, D
MouseGetPos, B2X, B2Y
Sleep, 200
action2:
  {
    MouseGetPos, xpos, ypos
    MouseClick, right, %B2X%, %B2Y%, ,0
    MouseClick, left, %B1X%, %B1Y%, ,0
    Sleep, 200
    MouseMove, %xpos%,%ypos%
    return
  } 
}
return
;-----------------------------------------------
Ok3:
Gui, Submit, NoHide
Hotkey, %var3%, action3, On
return
Med:
{
MsgBox ,48 , , Selecione a pos de seu POke no Battle, 10
KeyWait, LButton, D
MouseGetPos, Bps1X, Bps1Y
MsgBox ,48 , , Selecione a pos da Medicine em sua Backpack, 10
KeyWait, LButton, D
MouseGetPos, Bps2X, Bps2Y
Sleep, 200
action3:
  {
    MouseGetPos, xpos, ypos
    MouseClick, right, %Bps2X%, %Bps2Y%, ,0
    MouseClick, left, %Bps1X%, %Bps1Y%, ,0
    Sleep, 200
    MouseMove, %xpos%,%ypos%
    return
  } 
}
return
;-----------------------------------------------
Ok4:
Gui, Submit, NoHide
Hotkey, %var4%, action4, On
return
Smed:
{
MsgBox ,48 , , Selecione a pos de seu Personagem, 10
KeyWait, LButton, D
MouseGetPos, Bpsm1X, Bpsm1Y
MsgBox ,48 , , Selecione a pos da Medicine em sua Backpack, 10
KeyWait, LButton, D
MouseGetPos, Bpsm2X, Bpsm2Y
Sleep, 200
action4:
  {
    MouseGetPos, xpos, ypos
    MouseClick, right, %Bpsm2X%, %Bpsm2Y%, ,0
    MouseClick, left, %Bpsm1X%, %Bpsm1Y%, ,0
    Sleep, 200
    MouseMove, %xpos%,%ypos%
    return
  } 
}
return
;-----------------------------------------------
Check1:
Gui, Submit, NoHide
if Check = 1
{
MsgBox,48, , WASD Ativado, 10
walk = 1
}
else
{
MsgBox,48, , WASD Desativado, 10
walk = 0
}
return
#if walk = 1
{
w::up
a::left
s::down
d::right
}
#if
;-----------------------------------------------
Ok5:
Gui, Submit, NoHide
Hotkey, %var5%, %Poke%, On
return
;-----------
Chandelure:
{
send {F6}
Sleep, 600
send {F7}	
Sleep, 600
send {F8}	
Sleep, 600	
Send {F5}
}
return
;-----------
VoirHeal:
{
send {F3}
Sleep, 600
send {F6}	
Sleep, 600
send {F7}	
Sleep, 600	
Send {F8}
Sleep, 600
Send {F5}
Sleep, 600
Send {F4}
}
return
;-----------
VoirGolden:
{
send {F3}
Sleep, 600
send {F6}	
Sleep, 600
Send {F8}
Sleep, 600
Send {F5}
Sleep, 600
Send {F4}
}
return
;-----------
SmeargleXatuAstonish:
{
send {F6}
Sleep, 600
send {F1}
Sleep, 600
send {F5}
Sleep, 600
send {F4}
Sleep, 600
send {F3}
Sleep, 600
}
return
;-----------
SmeargleXatuBlizzard:
{
send {F5}
Sleep, 600
send {F1}
Sleep, 600
send {F6}
Sleep, 600
send {F4}
Sleep, 600
send {F3}
Sleep, 600
}
return
;-----------
Typhlosion:
{
send {F6}
Sleep, 600
send {F7}
Sleep, 600
send {F8}
Sleep, 600
send {F9}
Sleep, 600
send {F5}
}
return
;-----------
SmeargleGhost:
{
send {F1}
Sleep, 900
send {F6}
Sleep, 600
send {F5}
Sleep, 600
send {F2}
Sleep, 600
send {F4}
}
return
;-----------
ShMime:
{
send {F7}
Sleep, 600
send {F6}
Sleep, 600
send {F5}
Sleep, 600
send {F9}
}
return
;-----------
ShEspeon:
{
send {F9}
Sleep, 600
send {F8}
Sleep, 600
send {F7}
Sleep, 600
send {F6}
}
return
;-----------
Smeargle8Spout:
{
send {F6}
Sleep, 600
send {F5}
Sleep, 600
send {F3}
Sleep, 600
send {F1}
Sleep, 600
send {F8}
Sleep, 600
send {F7}
}
return
;-----------
Smeargle8Inferno:
{
send {F6}
Sleep, 600
send {F5}
Sleep, 600
send {F3}
Sleep, 600
send {F1}
Sleep, 600
send {F7}
Sleep, 600
send {F8}
}
return
;-----------
Smeargle8Blizzard:
{
send {F1}
Sleep, 600
send {F6}
Sleep, 600
send {F5}
Sleep, 600
send {F3}
Sleep, 600
send {F7}
Sleep, 600
send {F8}
}
return
;-----------
Golem:
{
send {F8}
Sleep, 600
send {F6}
Sleep, 600
send {F5}
Sleep, 600
send {F4}
}
return
;-----------
ShFearow:
{
send {F5}
Sleep, 600
send {F7}
Sleep, 600
send {F6}
}
return
;-----------
Tropius:
{
send {F1}
Sleep, 600
send {F6}
Sleep, 600
send {F9}
Sleep, 600
send {F8}
Sleep, 600
send {F7}
Sleep, 600
send {F5}
}
return
;-----------
GiantKarp:
{
send {F8}
Sleep, 600
send {F7}
Sleep, 600
send {F6}
Sleep, 600
send {F4}
Sleep, 600
send {F3}
}
return
;-----------
;-----------------------------------------------
Ok6:
Gui, Submit, NoHide
Hotkey, %var6%, action6, On
return
Swap:
{
MsgBox ,48 , , Selecione a pos de seu slot de pokemon, 10
KeyWait, LButton, D
MouseGetPos, BpxX, BpxY
MsgBox ,48 , , Selecione a pos do pokemon que vai ser trocado, 10
KeyWait, LButton, D
MouseGetPos, Bpx2X, Bpx2Y
Sleep, 200
action6:
  {
    MouseGetPos, xpos, ypos
	MouseClick, right, %BpxX%, %BpxY%, ,0
	Sleep, 80
    MouseMove, %Bpx2X%, %Bpx2Y%
	send,{Lbutton down}
	keywait,left
    MouseMove, %BpxX%, %BpxY%
	send,{Lbutton up}
    Sleep, 80
	MouseClick, right, %BpxX%, %BpxY%, ,0
	Sleep, 230
    MouseMove, %xpos%,%ypos%
    return
  } 
}
return
;-----------------------------------------------
Ok7:
Gui, Submit, NoHide
Hotkey, %var7%, action7, On
return
Heal:
{
MsgBox ,48 , , Selecione a pos de seu Poke no Battle, 10
KeyWait, LButton, D
MouseGetPos, B1hX, B1hY
MsgBox ,48 , , Selecione a pos do Elixir em sua Backpack, 10
KeyWait, LButton, D
MouseGetPos, B2hX, B2hY
Sleep, 200
action7:
  {
    MouseGetPos, xpos, ypos
    MouseClick, right, %B2hX%, %B2hY%, ,0
    MouseClick, left, %B1hX%, %B1hY%, ,0
    Sleep, 200
    MouseMove, %xpos%,%ypos%
    return
  } 
}
return
;-----------------------------------------------
Ok8:
Gui, Submit, NoHide
Hotkey, %var8%, action8, On
return
Attack:
{
MsgBox ,48 , , Selecione a pos de seu Poke no Battle, 10
KeyWait, LButton, D
MouseGetPos, Ba1X, Ba1Y
MsgBox ,48 , , Selecione a pos do Elixir em sua Backpack, 10
KeyWait, LButton, D
MouseGetPos, Ba2X, Ba2Y
Sleep, 200
action8:
  {
    MouseGetPos, xpos, ypos
    MouseClick, right, %Ba2X%, %Ba2Y%, ,0
    MouseClick, left, %Ba1X%, %Ba1Y%, ,0
    Sleep, 200
    MouseMove, %xpos%,%ypos%
    return
  } 
}
return
;-----------------------------------------------
Ok9:
Gui, Submit, NoHide
Hotkey, %var9%, action9, On
return
Defense:
{
MsgBox ,48 , , Selecione a pos de seu Poke no Battle, 10
KeyWait, LButton, D
MouseGetPos, Bd1X, Bd1Y
MsgBox ,48 , , Selecione a pos do Elixir em sua Backpack, 10
KeyWait, LButton, D
MouseGetPos, Bd2X, Bd2Y
Sleep, 200
action9:
  {
    MouseGetPos, xpos, ypos
    MouseClick, right, %Bd2X%, %Bd2Y%, ,0
    MouseClick, left, %Bd1X%, %Bd1Y%, ,0
    Sleep, 200
    MouseMove, %xpos%,%ypos%
    return
  } 
}
return
;-----------------------------------------------
Ok10:
Gui, Submit, NoHide
Hotkey, %var10%, action10, On
return
Run:
{
MsgBox ,48 , , Selecione a pos de seu Personagem, 10
KeyWait, LButton, D
MouseGetPos, Br1X, Br1Y
MsgBox ,48 , , Selecione a pos do Elixir em sua Backpack, 10
KeyWait, LButton, D
MouseGetPos, Br2X, Br2Y
Sleep, 200
action10:
  {
    MouseGetPos, xpos, ypos
    MouseClick, right, %Br2X%, %Br2Y%, ,0
    MouseClick, left, %Br1X%, %Br1Y%, ,0
    Sleep, 200
    MouseMove, %xpos%,%ypos%
    return
  } 
}
return
;-----------------------------------------------
Ok11:
Gui, Submit, NoHide
Hotkey, %var11%, action11, On
return
Corp: 
{
MsgBox ,48 , , Selecione a Posicao do Primeiro Monstro, 10
KeyWait, LButton, D
MouseGetPos, Bp1L, Bp1LY
MsgBox ,48 , , Selecione a Posicao do Segundo Monstro, 10
KeyWait, LButton, D
MouseGetPos, Bp2L, Bp2LY
MsgBox ,48 , , Selecione a Posicao do Terceiro Monstro, 10
KeyWait, LButton, D
MouseGetPos, Bp3L, Bp3LY
MsgBox ,48 , , Selecione a Posicao do Quarto Monstro, 10
KeyWait, LButton, D
MouseGetPos, Bp4L, Bp4LY
MsgBox ,48 , , Selecione a Posicao do Quinto Monstro, 10
KeyWait, LButton, D
MouseGetPos, Bp5L, Bp5LY
MsgBox ,48 , , Selecione a Posicao do Sexto Monstro, 10
KeyWait, LButton, D
MouseGetPos, Bp6L, Bp6LY
MsgBox ,48 , , Selecione a Posicao do Setimo Monstro, 10
KeyWait, LButton, D
MouseGetPos, Bp7L, Bp7LY
MsgBox ,48 , , Selecione a Posicao do Oitavo Monstro, 10
KeyWait, LButton, D
MouseGetPos, Bp8L, Bp8LY
Sleep, 200

action11:
  {
    MouseGetPos, xpos, ypos
    MouseClick, right, %Bp1L%, %Bp1LY%, ,0
	Sleep, 190
	MouseClick, right, %Bp2L%, %Bp2LY%, ,0
	Sleep, 190
	MouseClick, right, %Bp3L%, %Bp3LY%, ,0
	Sleep, 190
    MouseClick, right, %Bp4L%, %Bp4LY%, ,0
	Sleep, 190
	MouseClick, right, %Bp5L%, %Bp5LY%, ,0
	Sleep, 190
	MouseClick, right, %Bp6L%, %Bp6LY%, ,0
	Sleep, 190
	MouseClick, right, %Bp7L%, %Bp7LY%, ,0
	Sleep, 190
	MouseClick, right, %Bp8L%, %Bp8LY%, ,0
	Sleep, 190
    MouseMove, %xpos%,%ypos%
    return
  } 
}
return
;-----------------------------------------------
Fish:
{
Gui, Submit, nohide
vard := vard * 1000
MsgBox ,48 , , Selecione a posição onde vai pescar, 10
KeyWait, LButton, D
MouseGetPos, Bs23X, Bs23Y
actionf:
{
Send {Ctrl down}
Send {z}
Send {Ctrl up}
sleep, 500
MouseClick, left, %Bs23X%, %Bs23Y%, ,0
sleep, 700
Sleep, %vard%
Send {Ctrl down}
Send {z}
Send {Ctrl up}
sleep, 1500
return
}
return
}
return
;-----------------------------------------------
^j::
if toggle := !toggle
{
ToolTip ,Fishing ON, 350,9
WinGet, nom, ID, A
Settimer, actionf,   500
}
else
{
ToolTip
Settimer, actionf,   off
}
return
;-----------------------------------------------
Enviar_Mensagens:
#If (msg)
{
Sleep, 6000
Send {%vart%}
}
#if
msgin:
Gui Submit, NoHide
if(msg)
{
MsgBox ,48 , , Msg automáticas ativadas!, 10.
SetTimer, Enviar_Mensagens, 120000
}
else
{
SetTimer, Enviar_Mensagens, Off
MsgBox ,48 , , Msg automáticas desativadas!, 10.
}
Return
;-----------------------------------------------
^h::Suspend